import { z } from "zod";

export const profileSchema = z.object({
  fullName: z.string().min(1, "Full name is required").max(120),
  email: z.string().email("Invalid email address").optional().or(z.literal("")),
  registrationNumber: z.string().max(40).optional().or(z.literal("")),
  department: z.string().max(80).optional().or(z.literal("")),
  phone: z.string().max(30).optional().or(z.literal("")),
  preferredLanguage: z.string().max(40).optional().or(z.literal("")),
  timezone: z.string().max(80).optional().or(z.literal("")),
  bio: z.string().max(1000).optional().or(z.literal("")),
  designation: z.string().max(80).optional().or(z.literal("")),
  expertise: z.string().max(160).optional().or(z.literal("")),
  examTarget: z.string().max(80).optional().or(z.literal("")),
  caLevel: z.enum(["foundation", "ipc", "final"]).optional(),
  examTargetMonth: z.coerce.number().min(1).max(12).optional(),
  examTargetYear: z.coerce.number().min(2000).max(2100).optional(),
  isPublicProfile: z.coerce.boolean().default(true),
  batch: z.string().max(60).optional().or(z.literal("")),
  dob: z.string().max(40).optional().or(z.literal("")),
  location: z.string().max(80).optional().or(z.literal("")),
  firm: z.string().max(120).optional().or(z.literal("")),
  firmRole: z.string().max(80).optional().or(z.literal("")),
  articleshipYear: z.coerce.number().min(0).max(10).optional(),
  articleshipTotal: z.coerce.number().min(0).max(10).optional(),
  foundationCleared: z.coerce.boolean().default(false),
  intermediateCleared: z.coerce.boolean().default(false),
  finalCleared: z.coerce.boolean().default(false),
  resumeUrl: z.string().url("Invalid URL format").max(2048).optional().or(z.literal("")),
});
